"""
Django settings for plresearch project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load the same project-root .env the researcher pipeline (research/phase1)
# reads, so Django and the pipeline share one DB config.
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)!ys6=p9t!4he1gizp&rqgvzfmot84g)!2j#@mz3(ncu9*3fzl'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'research.apps.ResearchConfig',
    'products.apps.ProductsConfig',
    'tailwind',
    'theme',
]

TAILWIND_APP_NAME = 'theme'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'plresearch.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # global templates (e.g. base.html)
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'plresearch.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Points at the same PostgreSQL DB the researcher pipeline uses. Credentials
# come from .env. The password may contain '@'/':' (e.g. H@mza), so we split
# the host off the LAST '@' instead of using a URL parser — matching the
# tolerant parser in research/phase1/db.py. No percent-encoding required.

def _db_config_from_env():
    host = os.environ.get("DB_HOST")
    name = os.environ.get("DB_NAME")
    user = os.environ.get("DB_USER")

    if host and name and user:
        return {
            "HOST": host,
            "PORT": os.environ.get("DB_PORT", "5432"),
            "NAME": name,
            "USER": user,
            "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        }

    url = os.environ.get("DATABASE_URL")
    if not url:
        raise RuntimeError(
            "No database config in .env. Set DATABASE_URL or the discrete "
            "DB_HOST/DB_PORT/DB_NAME/DB_USER/DB_PASSWORD vars."
        )
    rest = re.sub(r"^\w+://", "", url.strip())
    userinfo, hostpart = rest.rsplit("@", 1)        # last '@' splits creds from host
    user, _, password = userinfo.partition(":")
    hostport, _, dbname = hostpart.partition("/")
    dbname = dbname.split("?")[0]
    host, _, port = hostport.partition(":")
    return {
        "HOST": host or "localhost",
        "PORT": port or "5432",
        "NAME": dbname,
        "USER": user,
        "PASSWORD": password,
    }


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        **_db_config_from_env(),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# Project-wide static sources (your own CSS/JS), searched in development.
STATICFILES_DIRS = [BASE_DIR / 'static']
# Destination for `collectstatic` in production (served by the web server).
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files — user uploads (Black Box / Xray exports) and generated output
# such as the Excel shortlists the researcher writes.
# https://docs.djangoproject.com/en/5.2/topics/files/
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Phase 3 fallback: when JS-sheet scraping fails (Amazon block / no working
# proxy), Phase 3 uses this manually-provided Jungle Scout sheet instead.
# Override via the PHASE3_FALLBACK_JS env var; defaults to the sample file.
PHASE3_FALLBACK_JS = os.environ.get(
    "PHASE3_FALLBACK_JS", str(BASE_DIR / "test_file" / "js-keyword-search.csv"))

# Phase 4 Keepa source. The default (no-API) path expects the user to upload a
# Keepa website export; the live Keepa API code is retained but only used when
# this flag is on (set PHASE4_USE_KEEPA_API=1 for dev/live-API runs).
PHASE4_USE_KEEPA_API = os.environ.get("PHASE4_USE_KEEPA_API", "").lower() in ("1", "true", "yes")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
