# Generated by Django 5.2.15 on 2026-06-14 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # `products` and `product_history` are managed=False (Django never issues
        # DDL for them) — they were created by the now-removed Phase-1 ingest raw
        # SQL. Create them here (idempotently) BEFORE the managed tables below,
        # whose foreign keys reference products(asin), so a fresh database (e.g.
        # Supabase prod) migrates cleanly. IF NOT EXISTS makes it a no-op where
        # the tables already exist; reverse is a no-op so rollback never drops
        # these data-bearing external tables.
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS products (
                asin varchar(20) NOT NULL PRIMARY KEY,
                title text NULL,
                brand varchar(255) NULL,
                category varchar(255) NULL,
                subcategory varchar(255) NULL,
                price numeric(12,2) NULL,
                bsr integer NULL,
                estimated_sales numeric(14,2) NULL,
                estimated_revenue numeric(14,2) NULL,
                review_count integer NULL,
                rating double precision NULL,
                weight_kg double precision NULL,
                yoy_growth double precision NULL,
                is_seasonal boolean NULL,
                variation_count integer NULL,
                has_variants boolean NULL,
                is_amazon_seller boolean NULL,
                is_compatibility boolean NULL,
                is_global_brand boolean NULL,
                fulfillment varchar(50) NULL,
                image_url text NULL,
                url text NULL,
                listing_age_months double precision NULL,
                sales_trend_90d double precision NULL,
                price_trend_90d double precision NULL,
                price_range varchar(10) NULL,
                review_bucket varchar(10) NULL,
                sales_bucket varchar(10) NULL,
                competition_score double precision NULL,
                demand_score double precision NULL,
                opportunity_score double precision NULL,
                llm_adj double precision NULL,
                llm_reason text NULL,
                llm_at timestamptz NULL,
                created_at timestamptz NOT NULL DEFAULT now(),
                last_updated timestamptz NOT NULL DEFAULT now()
            );
            CREATE INDEX IF NOT EXISTS idx_products_category ON products (category);
            CREATE INDEX IF NOT EXISTS idx_products_price_range ON products (price_range);
            CREATE INDEX IF NOT EXISTS idx_products_opportunity ON products (opportunity_score DESC);
            CREATE INDEX IF NOT EXISTS idx_products_has_variants ON products (has_variants);
            CREATE INDEX IF NOT EXISTS idx_products_is_seasonal ON products (is_seasonal);

            CREATE TABLE IF NOT EXISTS product_history (
                id bigserial NOT NULL PRIMARY KEY,
                asin varchar(20) NOT NULL,
                price numeric(12,2) NULL,
                bsr integer NULL,
                estimated_sales numeric(14,2) NULL,
                review_count integer NULL,
                captured_at timestamptz NOT NULL DEFAULT now()
            );
            CREATE INDEX IF NOT EXISTS idx_history_asin ON product_history (asin);
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bsr', models.IntegerField(blank=True, null=True)),
                ('estimated_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('yoy_growth', models.FloatField(blank=True, null=True)),
                ('is_seasonal', models.BooleanField(blank=True, null=True)),
                ('variation_count', models.IntegerField(blank=True, null=True)),
                ('has_variants', models.BooleanField(blank=True, null=True)),
                ('is_amazon_seller', models.BooleanField(blank=True, null=True)),
                ('is_compatibility', models.BooleanField(blank=True, null=True)),
                ('is_global_brand', models.BooleanField(blank=True, null=True)),
                ('fulfillment', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('listing_age_months', models.FloatField(blank=True, null=True)),
                ('sales_trend_90d', models.FloatField(blank=True, null=True)),
                ('price_trend_90d', models.FloatField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=10, null=True)),
                ('review_bucket', models.CharField(blank=True, max_length=10, null=True)),
                ('sales_bucket', models.CharField(blank=True, max_length=10, null=True)),
                ('competition_score', models.FloatField(blank=True, null=True)),
                ('demand_score', models.FloatField(blank=True, null=True)),
                ('opportunity_score', models.FloatField(blank=True, null=True)),
                ('llm_adj', models.FloatField(blank=True, null=True)),
                ('llm_reason', models.TextField(blank=True, null=True)),
                ('llm_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bsr', models.IntegerField(blank=True, null=True)),
                ('estimated_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReviewsInsights',
            fields=[
                ('product', models.OneToOneField(db_column='asin', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='insight', serialize=False, to='products.product')),
                ('weaknesses', models.JSONField(blank=True, default=list)),
                ('solutions', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Product reviews insights',
                'db_table': 'product_reviews_insights',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=255)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('review_date', models.CharField(blank=True, max_length=255, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=10, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='asin', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'db_table': 'product_reviews',
                'indexes': [models.Index(fields=['product'], name='idx_reviews_asin'), models.Index(fields=['stars'], name='idx_reviews_stars')],
                'constraints': [models.UniqueConstraint(fields=('product', 'review_id'), name='uq_review_per_product')],
            },
        ),
    ]
