# Generated by Django 5.2.15 on 2026-06-14 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('asin', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bsr', models.IntegerField(blank=True, null=True)),
                ('estimated_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('yoy_growth', models.FloatField(blank=True, null=True)),
                ('is_seasonal', models.BooleanField(blank=True, null=True)),
                ('variation_count', models.IntegerField(blank=True, null=True)),
                ('has_variants', models.BooleanField(blank=True, null=True)),
                ('is_amazon_seller', models.BooleanField(blank=True, null=True)),
                ('is_compatibility', models.BooleanField(blank=True, null=True)),
                ('is_global_brand', models.BooleanField(blank=True, null=True)),
                ('fulfillment', models.CharField(blank=True, max_length=50, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('listing_age_months', models.FloatField(blank=True, null=True)),
                ('sales_trend_90d', models.FloatField(blank=True, null=True)),
                ('price_trend_90d', models.FloatField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=10, null=True)),
                ('review_bucket', models.CharField(blank=True, max_length=10, null=True)),
                ('sales_bucket', models.CharField(blank=True, max_length=10, null=True)),
                ('competition_score', models.FloatField(blank=True, null=True)),
                ('demand_score', models.FloatField(blank=True, null=True)),
                ('opportunity_score', models.FloatField(blank=True, null=True)),
                ('llm_adj', models.FloatField(blank=True, null=True)),
                ('llm_reason', models.TextField(blank=True, null=True)),
                ('llm_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bsr', models.IntegerField(blank=True, null=True)),
                ('estimated_sales', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('review_count', models.IntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductReviewsInsights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=20)),
                ('common_complaints', models.TextField(blank=True, null=True)),
                ('negative_keywords', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Product reviews insights',
                'db_table': 'product_reviews_insights',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=255)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('review_date', models.CharField(blank=True, max_length=255, null=True)),
                ('marketplace', models.CharField(blank=True, max_length=10, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(db_column='asin', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
            ],
            options={
                'db_table': 'product_reviews',
                'indexes': [models.Index(fields=['product'], name='idx_reviews_asin'), models.Index(fields=['stars'], name='idx_reviews_stars')],
                'constraints': [models.UniqueConstraint(fields=('product', 'review_id'), name='uq_review_per_product')],
            },
        ),
    ]
